#!/bin/bash

FILE_PATH="~/.config/hypr/binds.conf"
CURRENT_MODE=""
GAMES=("dota2" "factorio" "terraria")
GAME=""

is_game_running(){
  declare -g GAME=""
  for game in "${GAMES[@]}"; do
    if pgrep -x "$game" > /dev/null; then
      GAME="$game"
      return 0
    fi
  done
  return 1
}

get_mode(){
  if is_game_running; then
    CURRENT_MODE="GAMING"
  else
    CURRENT_MODE="NORMAL"
  fi
  echo $CURRENT_MODE
}

file_exist(){
  if [ ! -e "$FILE_PATH" ]; then
      echo "Error: File not found at $FILE_PATH"
      exit 1
  fi
}


set_keybinds(){
  if [ "$(get_mode)" = "GAMING" ]; then
    echo "source = ~/.config/hypr/scripts/gamemode.conf" > ~/.config/hypr/gamemode.conf
    printf '{"text": "Gaming", "class": "on", "tooltip":"%s", "alt":"1"}\n' "$GAME"
  else
    echo "" > ~/.config/hypr/gamemode.conf
    printf '{"text": "", "class": "off","alt":"0", "tooltip":"%s"}\n' "Not Playing"
  fi
}

set_keybinds
echo $GAME
