-- local configs = require("lspconfig.configs")
-- local util = require("lspconfig.util")
--
-- local qlik_settings = { linter = { active = true } }
--
-- if not configs.qlik_ls then
--   configs.qlik_ls = {
--     default_config = {
--       cmd = { "qlik-ls" },
--       filetypes = { "qvs" },
--       root_dir = util.root_pattern(".git", "."),
--       single_file_support = true,
--       settings = qlik_settings,
--     },
--   }
-- end

